export interface PlatformDefinition {
  key: string;
  name: string;
  version: string;
  category: "ecommerce" | "marketplace" | "generic";
  /** Import source, export destination, or both */
  direction: "import" | "export" | "both";
  blurb: string;
  /** Header signals used for auto-detection (normalized lowercase) */
  detectSignals: string[];
  /** Default product column → Shopify field map */
  productMappings: Record<string, string>;
}

/** Expanded cross-platform catalog for import/export + auto-detect. */
export const PLATFORM_CATALOG: PlatformDefinition[] = [
  {
    key: "shopify",
    name: "Shopify",
    version: "native",
    category: "ecommerce",
    direction: "both",
    blurb: "Native Shopify CSV / Admin format",
    detectSignals: ["handle", "variant sku", "variant price", "body (html)", "variant inventory qty"],
    productMappings: {
      Title: "title",
      "Body (HTML)": "descriptionHtml",
      Vendor: "vendor",
      Type: "productType",
      Tags: "tags",
      "Variant SKU": "variants.sku",
      "Variant Price": "variants.price",
      "Variant Compare At Price": "variants.compareAtPrice",
      "Variant Inventory Qty": "variants.inventoryQuantity",
      "Image Src": "images",
    },
  },
  {
    key: "woocommerce",
    name: "WooCommerce",
    version: "v8",
    category: "ecommerce",
    direction: "both",
    blurb: "WordPress WooCommerce product export",
    detectSignals: ["regular price", "short description", "stock", "published"],
    productMappings: {
      Name: "title",
      SKU: "variants.sku",
      "Regular price": "variants.price",
      "Sale price": "variants.compareAtPrice",
      Stock: "variants.inventoryQuantity",
      Description: "descriptionHtml",
      "Short description": "descriptionHtml",
      Categories: "productType",
      Tags: "tags",
      Images: "images",
      Weight: "variants.weight",
    },
  },
  {
    key: "bigcommerce",
    name: "BigCommerce",
    version: "v3",
    category: "ecommerce",
    direction: "both",
    blurb: "BigCommerce catalog spreadsheet",
    detectSignals: ["product name", "current stock", "sale price", "product image url"],
    productMappings: {
      "Product Name": "title",
      SKU: "variants.sku",
      Price: "variants.price",
      "Sale Price": "variants.compareAtPrice",
      "Current Stock": "variants.inventoryQuantity",
      Description: "descriptionHtml",
      Category: "productType",
      "Product Image URL": "images",
      Weight: "variants.weight",
    },
  },
  {
    key: "magento",
    name: "Magento / Adobe",
    version: "v2",
    category: "ecommerce",
    direction: "both",
    blurb: "Magento / Adobe Commerce export",
    detectSignals: ["qty", "attribute_set_code", "product_type", "base_image"],
    productMappings: {
      sku: "variants.sku",
      name: "title",
      price: "variants.price",
      special_price: "variants.compareAtPrice",
      qty: "variants.inventoryQuantity",
      description: "descriptionHtml",
      short_description: "descriptionHtml",
      weight: "variants.weight",
      base_image: "images",
      categories: "productType",
    },
  },
  {
    key: "squarespace",
    name: "Squarespace",
    version: "v1",
    category: "ecommerce",
    direction: "both",
    blurb: "Squarespace Commerce CSV",
    detectSignals: ["product url", "on sale", "host"],
    productMappings: {
      Title: "title",
      Description: "descriptionHtml",
      SKU: "variants.sku",
      Price: "variants.price",
      "Sale Price": "variants.compareAtPrice",
      "Stock": "variants.inventoryQuantity",
      Categories: "productType",
      Tags: "tags",
    },
  },
  {
    key: "etsy",
    name: "Etsy",
    version: "v1",
    category: "marketplace",
    direction: "both",
    blurb: "Etsy listing CSV",
    detectSignals: ["listing id", "quantity", "who_made", "when_made"],
    productMappings: {
      TITLE: "title",
      DESCRIPTION: "descriptionHtml",
      SKU: "variants.sku",
      PRICE: "variants.price",
      QUANTITY: "variants.inventoryQuantity",
      TAGS: "tags",
      MATERIALS: "productType",
    },
  },
  {
    key: "wix",
    name: "Wix",
    version: "v1",
    category: "ecommerce",
    direction: "both",
    blurb: "Wix Stores product export",
    detectSignals: ["productname", "collection", "discountmode"],
    productMappings: {
      name: "title",
      productName: "title",
      description: "descriptionHtml",
      sku: "variants.sku",
      price: "variants.price",
      discountedPrice: "variants.compareAtPrice",
      inventory: "variants.inventoryQuantity",
      collection: "productType",
    },
  },
  {
    key: "amazon",
    name: "Amazon",
    version: "flatfile",
    category: "marketplace",
    direction: "both",
    blurb: "Amazon Seller flat file / inventory report",
    detectSignals: ["item-name", "seller-sku", "asin", "fulfillment-channel"],
    productMappings: {
      "item-name": "title",
      "item-description": "descriptionHtml",
      "seller-sku": "variants.sku",
      "standard-price": "variants.price",
      "sale-price": "variants.compareAtPrice",
      quantity: "variants.inventoryQuantity",
      "main-image-url": "images",
      "product-type": "productType",
    },
  },
  {
    key: "ebay",
    name: "eBay",
    version: "fileexchange",
    category: "marketplace",
    direction: "both",
    blurb: "eBay File Exchange format",
    detectSignals: ["*title", "*c:condition", "customlabel", "startprice"],
    productMappings: {
      "*Title": "title",
      Title: "title",
      Description: "descriptionHtml",
      CustomLabel: "variants.sku",
      "*StartPrice": "variants.price",
      StartPrice: "variants.price",
      "*Quantity": "variants.inventoryQuantity",
      Quantity: "variants.inventoryQuantity",
      PicURL: "images",
    },
  },
  {
    key: "prestashop",
    name: "PrestaShop",
    version: "v8",
    category: "ecommerce",
    direction: "both",
    blurb: "PrestaShop product CSV",
    detectSignals: ["id_product", "reference", "quantity", "id_category_default"],
    productMappings: {
      Name: "title",
      name: "title",
      Reference: "variants.sku",
      reference: "variants.sku",
      Price: "variants.price",
      price_tax_excl: "variants.price",
      Quantity: "variants.inventoryQuantity",
      quantity: "variants.inventoryQuantity",
      Description: "descriptionHtml",
      description: "descriptionHtml",
      Categories: "productType",
    },
  },
  {
    key: "opencart",
    name: "OpenCart",
    version: "v3",
    category: "ecommerce",
    direction: "both",
    blurb: "OpenCart product export",
    detectSignals: ["model", "product_description", "subtract"],
    productMappings: {
      name: "title",
      model: "variants.sku",
      sku: "variants.sku",
      price: "variants.price",
      quantity: "variants.inventoryQuantity",
      description: "descriptionHtml",
      image: "images",
    },
  },
  {
    key: "google_merchant",
    name: "Google Merchant",
    version: "v1",
    category: "marketplace",
    direction: "both",
    blurb: "Google Merchant Center product feed",
    detectSignals: ["g:id", "g:title", "g:price", "g:availability", "id", "availability"],
    productMappings: {
      title: "title",
      description: "descriptionHtml",
      id: "variants.sku",
      "g:id": "variants.sku",
      price: "variants.price",
      "g:price": "variants.price",
      "sale price": "variants.compareAtPrice",
      image_link: "images",
      "g:image_link": "images",
      brand: "vendor",
      "product type": "productType",
    },
  },
  {
    key: "square",
    name: "Square",
    version: "v1",
    category: "ecommerce",
    direction: "both",
    blurb: "Square item library CSV",
    detectSignals: ["token", "item name", "variation name", "default unit cost"],
    productMappings: {
      "Item Name": "title",
      Description: "descriptionHtml",
      SKU: "variants.sku",
      Price: "variants.price",
      "Current Quantity": "variants.inventoryQuantity",
      Categories: "productType",
    },
  },
  {
    key: "lightspeed",
    name: "Lightspeed",
    version: "v1",
    category: "ecommerce",
    direction: "both",
    blurb: "Lightspeed Retail / eCom export",
    detectSignals: ["systemid", "customsku", "defaultcost", "qoh"],
    productMappings: {
      Description: "title",
      "Custom SKU": "variants.sku",
      Price: "variants.price",
      QOH: "variants.inventoryQuantity",
      Category: "productType",
    },
  },
  {
    key: "ecwid",
    name: "Ecwid",
    version: "v1",
    category: "ecommerce",
    direction: "both",
    blurb: "Ecwid product CSV",
    detectSignals: ["product url", "unlimited", "is shipping required"],
    productMappings: {
      name: "title",
      sku: "variants.sku",
      price: "variants.price",
      quantity: "variants.inventoryQuantity",
      description: "descriptionHtml",
      category: "productType",
    },
  },
  {
    key: "tiktok_shop",
    name: "TikTok Shop",
    version: "v1",
    category: "marketplace",
    direction: "both",
    blurb: "TikTok Shop product template",
    detectSignals: ["product_id", "sale_price", "warehouse_id", "sku_id"],
    productMappings: {
      product_name: "title",
      product_description: "descriptionHtml",
      seller_sku: "variants.sku",
      price: "variants.price",
      sale_price: "variants.compareAtPrice",
      quantity: "variants.inventoryQuantity",
      main_image: "images",
    },
  },
  {
    key: "facebook_catalog",
    name: "Meta Catalog",
    version: "v1",
    category: "marketplace",
    direction: "both",
    blurb: "Facebook / Instagram commerce catalog",
    detectSignals: ["availability", "condition", "link", "image_link", "gtin"],
    productMappings: {
      title: "title",
      description: "descriptionHtml",
      id: "variants.sku",
      price: "variants.price",
      "sale_price": "variants.compareAtPrice",
      image_link: "images",
      brand: "vendor",
      "product_type": "productType",
    },
  },
  {
    key: "shift4shop",
    name: "Shift4Shop",
    version: "v1",
    category: "ecommerce",
    direction: "both",
    blurb: "Shift4Shop (3dcart) export",
    detectSignals: ["catalogid", "sdescription", "mfid"],
    productMappings: {
      name: "title",
      description: "descriptionHtml",
      sku: "variants.sku",
      price: "variants.price",
      stock: "variants.inventoryQuantity",
    },
  },
  {
    key: "csv",
    name: "Generic CSV",
    version: "any",
    category: "generic",
    direction: "both",
    blurb: "Unknown / custom spreadsheet — AI + fuzzy match columns",
    detectSignals: [],
    productMappings: {
      title: "title",
      name: "title",
      product_name: "title",
      description: "descriptionHtml",
      sku: "variants.sku",
      price: "variants.price",
      compare_at_price: "variants.compareAtPrice",
      inventory: "variants.inventoryQuantity",
      quantity: "variants.inventoryQuantity",
      stock: "variants.inventoryQuantity",
      tags: "tags",
      vendor: "vendor",
      type: "productType",
      image: "images",
      images: "images",
    },
  },
];

export const SUPPORTED_PLATFORMS = PLATFORM_CATALOG.map((p) => ({
  key: p.key,
  name: p.name,
  version: p.version,
}));

export type PlatformKey = string;

export function getPlatform(key: string): PlatformDefinition | undefined {
  return PLATFORM_CATALOG.find((p) => p.key === key);
}

export function platformsForImport(): PlatformDefinition[] {
  return PLATFORM_CATALOG.filter((p) => p.direction === "import" || p.direction === "both");
}

export function platformsForExport(): PlatformDefinition[] {
  return PLATFORM_CATALOG.filter((p) => p.direction === "export" || p.direction === "both");
}
