import Link from "next/link";
import { MarketingShell } from "../components/MarketingShell";

export const metadata = {
  title: "Privacy Policy — TidySync",
  description: "Privacy Policy for the TidySync Shopify application.",
};

export default function PrivacyPage() {
  return (
    <MarketingShell active="privacy">
      <div className="ts-container ts-legal">
        <h1>Privacy Policy</h1>
        <p className="updated">Last updated: August 30, 2026</p>
        <article>
          <p>
            This Privacy Policy explains how TidySync (&quot;we&quot;, &quot;us&quot;) collects,
            uses, and shares information when you install or use our Shopify app and related
            websites (including documentation and legal pages).
          </p>

          <h2>1. Scope</h2>
          <p>
            This policy covers merchant stores that install TidySync, users who access the embedded
            dashboard, and visitors to public pages such as this policy.
          </p>

          <h2>2. Information we collect</h2>
          <p>
            <strong className="ts-legal-strong">From Shopify (after you install):</strong>
          </p>
          <ul>
            <li>Shop domain and basic shop profile information</li>
            <li>OAuth offline access tokens required to call Shopify Admin APIs on your behalf</li>
            <li>
              Catalog and related resources you choose to import, export, scan, or edit (e.g.
              products, collections, customers, metafields as permitted by granted scopes)
            </li>
            <li>Billing-related identifiers for subscriptions and one-time charges via Shopify Billing</li>
          </ul>
          <p>
            <strong className="ts-legal-strong">Generated by the App:</strong>
          </p>
          <ul>
            <li>Job history, previews, diffs, snapshots for undo, audit logs</li>
            <li>Mapping templates, schedules, notification preferences</li>
            <li>Plan, credit usage, and feature settings for your store</li>
          </ul>
          <p>
            <strong className="ts-legal-strong">From visitors to public pages:</strong> standard web
            logs (IP, user agent, pages viewed) may be processed by our hosting provider for
            security and reliability.
          </p>

          <h2>3. How we use information</h2>
          <ul>
            <li>Provide, operate, and improve import, export, and bulk-edit features you request</li>
            <li>Authenticate embedded sessions and protect against abuse</li>
            <li>Process Shopify Billing charges you approve</li>
            <li>Provide support and troubleshoot failed jobs</li>
            <li>Comply with legal obligations and enforce our Terms</li>
          </ul>
          <p>
            We do <strong className="ts-legal-strong">not</strong> sell your store data. Processing
            only covers data needed for operations you initiate (for example, a bulk-edit request and
            relevant product fields).
          </p>

          <h2>4. Third-party processors</h2>
          <p>
            When you use assisted editing or content suggestions, relevant prompts and catalog
            snippets may be sent to subprocessors solely to generate plans or content for your
            request. Do not include sensitive personal data in prompts that is not needed for the
            task.
          </p>

          <h2>5. Sharing</h2>
          <p>We share data only with:</p>
          <ul>
            <li>Shopify, as required to operate an embedded app and billing</li>
            <li>Infrastructure providers (hosting, database, queue/redis) under contract</li>
            <li>Subprocessors as described above when you use assisted editing features</li>
            <li>Authorities when required by law</li>
          </ul>

          <h2>6. Retention</h2>
          <p>
            We retain tenant, job, and audit data while the App is installed and for a reasonable
            period afterward for backups, disputes, and legal compliance. After uninstall, we delete
            or anonymize personal and store data within a commercially reasonable timeframe, except
            where retention is required by law or for security logs.
          </p>

          <h2>7. Security</h2>
          <p>
            We use HTTPS, access controls, and least-privilege practices. No method of transmission
            or storage is 100% secure; please protect Shopify staff accounts with strong
            authentication.
          </p>

          <h2>8. Your choices</h2>
          <ul>
            <li>Uninstall the App from Shopify Admin to revoke access tokens</li>
            <li>Contact us to request deletion of retained tenant data where applicable</li>
            <li>Adjust notification emails inside the App settings</li>
          </ul>

          <h2>9. Children</h2>
          <p>The App is for business use and is not directed to children under 16.</p>

          <h2>10. International transfers</h2>
          <p>
            Data may be processed in the regions where our hosting and subprocessors operate. By
            using the App, you understand that processing may occur outside your country subject to
            appropriate safeguards.
          </p>

          <h2>11. Changes</h2>
          <p>
            We may update this policy and will revise the &quot;Last updated&quot; date. Material
            changes may also be communicated in-app or via Shopify where appropriate.
          </p>

          <h2>12. Contact</h2>
          <p>
            Privacy requests: contact us via the channel listed on{" "}
            <Link href="/" className="ts-text-link">
              sync.tidyflowapp.com
            </Link>{" "}
            or your TidySync support email.
          </p>
        </article>
      </div>
    </MarketingShell>
  );
}
